debug: true
server:
  host: "localhost"
  address: "9123"
context:
  timeout: 10
dir:
  sdk:
    src: "static/sdk/src"
    dst: "static/sdk/dst"
  uploadPath:
    oasPath: "static/upload/oas"
    sqlitePath: "wundergraph/.wundergraph"
    swaggerPath: "static/upload/swagger"
  ossUploadPath: "static/upload/oss"
  operationsSettingPath:
    operationPrefix: "static/operateapi/setting"
  operateAPIPath:
    prefix: "wundergraph/.wundergraph/operations"
  wunderGraphPath:
    generated: "wundergraph/.wundergraph/generated"
  settingDirPath: "static/setting"
  webStaticFront: "front"
  tpldirPathFront: "static/tpl"
  HookTypeFilePath: "wundergraph/.wundergraph/generated"

file:
  operateAPIPath:
    suffix: ".graphql"
    switchOff: ".off"
    switchOn: ""
  operationsSettingPath:
    globalPrefix: "static/operateapi/global_setting"
