services:
  - type: web
    name: fireboom
    env: node
    region: singapore
    repo: https://github.com/fireboomio/fb-init-simple.git
    buildCommand: echo ""
    startCommand: ./run.sh
    envVars:
      - key: DB_URL
        fromDatabase:
          name: fireboom
          property: connectionString
      - key: MINIO_ROOT_PASSWORD
        fromService:
          type: web
          name: minio
          envVarKey: MINIO_ROOT_PASSWORD

databases:
  - name: fireboom
    databaseName: fireboom
    ipAllowList: [] # only allow internal connections
