services:
  - type: web
    name: fireboom
    env: node
    region: singapore
    repo: https://github.com/fireboomio/fb-init-simple.git
    buildCommand: echo ""
    startCommand: ./run.sh
    envVars:
      - key: DB_URL
        fromDatabase:
          name: fireboom
          property: connectionString

databases:
  - name: fireboom
