services:
  - type: web
    name: minio
    env: docker
    region: singapore
    envVars:
    - key: MINIO_ROOT_PASSWORD
      generateValue: true # will generate a base64-encoded 256-bit secret
    - key: MINIO_ROOT_USER
      sync: false # placeholder for a value to be added in the dashboard
    - key: PORT
      value: 10000
    disk:
      name: data
      mountPath: /data
      sizeGB: 10 # optional
  - type: web
    name: fireboom
    env: node
    region: singapore
    repo: git@github.com:fireboomio/fb-init-simple.git
    buildCommand: echo ""
    startCommand: ./run.sh
    envVars:
      - key: DB_URL
        fromDatabase:
          name: fireboom
          property: connectionString
      - key: MINIO_ROOT_PASSWORD
        fromService:
          type: web
          name: minio
          envVarKey: MINIO_ROOT_PASSWORD

databases:
  - name: fireboom
    databaseName: fireboom
    ipAllowList: [] # only allow internal connections
